version: '3.8'

services:
  # Dịch vụ PHP
  php:
    image: php:8.1-apache
    container_name: php-server
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - web

  # Dịch vụ MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: QL
    ports:
      - "3306:3306"
    networks:
      - web
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  web:

volumes:
  mysql-data:
